exclude: [ Makefile, scripts ]

url:          http://robb.is
permalink:    /:categories/:title
markdown:     kramdown
highlighter:  pygments
paginate:     7
category_dir: ''
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

