auto:       false
server:     false
permalink:  /:categories/:title
markdown:   kramdown
exclude:    default.sass

category_dir: ''

embedly:
  api_key: edd850c4aa4c11e0b1524040d3dc5c07

  soundcloud:
    player_type: artwork
    color:       0066FF
    width:       600px
    height:      600px

  vimeo:
    width:  600
    byline: 0
    color:  FF0000

  youtube:
    width:    600
    maxwidth: 600

  flickr:
    width:    600
    maxwidth: 600
